### ISSUE TITLE
Compatibility with update 2.0.7 / Space-Age

### ISSUE THREAD

**Issue by theM94** [Suprcheese/Squeak-Through#18]
I got the mod working, simply by editing the factorio version ("factorio_version": "2.0",). And it works. Not for all objects, but good enough to be viable.

Would be nice if we could get an update that is compatible.

**Comment by Suprcheese** [comment]
Ok if it's that simple I can do a maintenance update. I wish I had time to play more Factorio, though... perhaps over Thanksgiving.
