### ISSUE TITLE
Proposed fix for compatibility issues

### ISSUE THREAD

**Issue by Foxite** [Suprcheese/Squeak-Through#7]
Squeak Through should look for a property named "squeak_behaviour" (or some other name) on modded entities. The property will allow mod authors to stop ST from causing problems with their entities.  
The property is a boolean where true tells ST to enable squeaking for this entity, and false tells it to ignore the entity.  
If the property does not exist, then the user will decide what to do with it, by changing a setting. Possible values for this setting:

- Opt-in: entities that do not specify squeak_behaviour will not be affected
- Opt-out: entities that do not specify squeak_behaviour will be affected
- Force: all entities will be affected, regardless of squeak_behaviour. The user should be warned not to report bugs when using this, as it effectively disables this whole system. I'm proposing this option for users who do not experience problems from the current state of ST, so that they won't have to change their muscle-memory.

I recommend that the default value for the user setting should be Opt-out, as it does not change the status quo for mods that don't utilize this.

I'm willing to implement this, ~~but I'll have to find the time to do so, and I can't tell when I can get started.~~ I have implemented this feature, see PR below.

**Comment by Foxite** [comment]
Disregard the last line, I have already this feature. PR #8

**Comment by Suprcheese** [comment]
Implemented in v1.4.0. Thank you for your contribution!
